# Generated by Django 5.0.2 on 2025-11-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=3)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('salon', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=255)),
                ('maestro', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
