# Generated by Django 5.0.2 on 2025-11-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0004_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='horario',
        ),
        migrations.AddField(
            model_name='materias',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materias',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
