# Generated by Django 5.0.2 on 2025-11-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0005_remove_materias_horario_materias_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
