# Generated by Django 5.0.2 on 2025-11-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0006_alter_materias_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
