# Generated by Django 5.0.2 on 2025-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0007_alter_materias_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materias',
            name='maestro',
            field=models.CharField(max_length=70),
        ),
    ]
